from pydantic import BaseModel, Field


class ApplyAPOnTrafficRequest(BaseModel):
    enable: bool = Field(alias="enable", description="""""")
    add_imsi_field_to_log: bool = Field(
        alias="add-imsi-field-to-log",
        description="""Add IMSI field to logs generated by user traffic.""",
    )
