from .pydantic import BaseModel, Field


class ApplicationsRequestNew(BaseModel):
    enable_print_mails: bool = Field(
        alias="enable-print-mails", description="""Allow to print mails."""
    )
    max_attachments_size: int = Field(
        alias="max-attachments-size",
        description="""Maximum size of attachments allowed for downloading -  you can choose a unit (gbs, kbs, mbs, bytes) in max-attachments-unit field.""",
    )
    calendar_from_the_last: int = Field(
        alias="calendar-from-the-last",
        description="""How far back to see your Calendar from .the current date - you can choose a unit (day, week, month) in calendar-from-the-last-unit field.""",
    )
    calendar_from_the_last_unit: str = Field(
        alias="calendar-from-the-last-unit",
        description="""Unit for calendar-from-the-last numeric value.""",
    )
    calendar_to_the_following: int = Field(
        alias="calendar-to-the-following",
        description="""How much ahead to see your Calendar from .the current date - you can choose a unit (day, week, month) in calendar-to-the-following-unit field.""",
    )
    calendar_to_the_following_unit: str = Field(
        alias="calendar-to-the-following-unit",
        description="""Unit for calendar-to-the-following numeric value.""",
    )
    mail_from_the_last: int = Field(
        alias="mail-from-the-last",
        description="""How far back to see your emails from .the current date - choose a unit (day, week, month) in mail-from-the-last-unit field.""",
    )
    mail_from_the_last_unit: str = Field(
        alias="mail-from-the-last-unit",
        description="""Unit for mail-from-the-last numeric value.""",
    )
    synchronize_contacts: str = Field(
        alias="synchronize-contacts",
        description="""Contacts synchronization method - from .the mail server to device and the app and vice versa or from .the mail server to device and the app or from .the mail server to the app.""",
    )
    allow_push_notification: bool = Field(
        alias="allow-push-notification",
        description="""Allow to receive push notifications of mails and meetings.""",
    )
    allow_calendar_sync: bool = Field(
        alias="allow-calendar-sync",
        description="""Allow synchronization between business calendar to device calendar.""",
    )
    allow_contacts_from_global_address_list: bool = Field(
        alias="allow-contacts-from-global-address-list",
        description="""Allow to add additional contacts from .Global Address List to the app.""",
    )
    allow_contacts_from_local_phone: bool = Field(
        alias="allow-contacts-from-local-phone",
        description="""Allow to add additional contacts from .local phone to the app.""",
    )
    save_local_web_cache: bool = Field(
        alias="save-local-web-cache",
        description="""Configure whether local cache data generated by web browser should be preserved.""",
    )
    allow_caching_docsec_credentials: bool = Field(
        alias="allow-caching-docsec-credentials",
        description="""Allow store encrypted document credentials in application secure storage.""",
    )
    allow_caching_docsec_keys: bool = Field(
        alias="allow-caching-docsec-keys",
        description="""Allow store encrypted document keys in application secure storage.""",
    )
