from .pydantic import BaseModel, Field


class MonitoringAndLoggingDomainPermissionsRequest(BaseModel):
    monitoring: str = Field(alias="monitoring", description="""See monitoring views and reports.""")
    management_logs: str = Field(
        alias="management-logs", description="""See Multi-Domain Server audit logs."""
    )
    track_logs: str = Field(
        alias="track-logs",
        description="""Use the log tracking features in SmartConsole.""",
    )
    app_and_url_filtering_logs: bool = Field(
        alias="app-and-url-filtering-logs",
        description="""Work with Application and URL Filtering logs.""",
    )
    https_inspection_logs: bool = Field(
        alias="https-inspection-logs",
        description="""See logs generated by HTTPS Inspection.""",
    )
    packet_capture_and_forensics: bool = Field(
        alias="packet-capture-and-forensics",
        description="""See logs generated by the IPS and Forensics features.""",
    )
    show_packet_capture_by_default: bool = Field(
        alias="show-packet-capture-by-default",
        description="""Enable packet capture by default.""",
    )
    identities: bool = Field(
        alias="identities",
        description="""Show user and computer identity information in logs.""",
    )
    show_identities_by_default: bool = Field(
        alias="show-identities-by-default",
        description="""Show user and computer identity information in logs by default.""",
    )
    dlp_logs_including_confidential_fields: bool = Field(
        alias="dlp-logs-including-confidential-fields",
        description="""Show DLP logs including confidential fields.""",
    )
    manage_dlp_messages: bool = Field(
        alias="manage-dlp-messages",
        description="""View/Release/Discard DLP messages.<br>Available only if dlp-logs-including-confidential-fields is set to true.""",
    )
