from .api_domain_identifier import ApiDomainIdentifier
from .available_actions_reply import AvailableActionsReply
from .meta_info_for_top_level_reply import MetaInfoForTopLevelReply
from .pydantic import BaseModel, Field


class ScadaApplicationReply(BaseModel):
    name: str = Field(alias="name", description="""Object name. Must be unique in the domain.""")
    uid: str = Field(alias="uid", description="""Object unique identifier.""")
    type: str = Field(alias="type", description="""Object type.""")
    additional_categories: list[str] = Field(alias="additional-categories", description="""N/A""")
    additional_categories_ids: list[str] = Field(
        alias="additional-categories-ids", description="""Additional categories Id's."""
    )
    application_id: int = Field(alias="application-id", description="""N/A""")
    application_signature: str = Field(
        alias="application-signature",
        description="""Application signature generated by <a href=https://support.checkpoint.com/results/sk/sk103051>Signature Tool</a>.""",
    )
    category: str = Field(alias="category", description="""SCADA application category.""")
    description: str = Field(alias="description", description="""N/A""")
    groups: list[dict] = Field(
        alias="groups",
        description="""Level of details in the output corresponds to the number of details for search. This table shows the level of details in the Standard level.""",
    )
    primary_category_id: str = Field(
        alias="primary-category-id", description="""Primary category id."""
    )
    risk: str = Field(alias="risk", description="""N/A""")
    scada_properties: list[dict] = Field(
        alias="scada-properties", description="""SCADA application properties."""
    )
    user_defined: bool = Field(
        alias="user-defined",
        description="""True if this application site was defined by user (not predefined one).""",
    )
    color: str = Field(
        alias="color",
        description="""Color of the object. Should be one of existing colors.""",
    )
    comments: str = Field(alias="comments", description="""Comments string.""")
    domain: ApiDomainIdentifier = Field(
        alias="domain",
        description="""Information about the domain that holds the Object.""",
    )
    icon: str = Field(alias="icon", description="""Object icon.""")
    meta_info: MetaInfoForTopLevelReply = Field(
        alias="meta-info", description="""Object metadata."""
    )
    read_only: bool = Field(
        alias="read-only", description="""Indicates whether the object is read-only."""
    )
    tags: list[dict] = Field(
        alias="tags",
        description="""Collection of tag objects identified by the name or UID. Level of details in the output corresponds to the number of details for search. This table shows the level of details in the Standard level.""",
    )
    available_actions: AvailableActionsReply = Field(
        alias="available-actions",
        description="""Actions that are available on the object.""",
    )
