from add import Add
from pydantic import BaseModel, Field
from remove import Remove
from scv_exceptions_request import ScvExceptionsRequest


class ScvGlobalPropertiesRequest(BaseModel):
    apply_scv_on_simplified_mode_fw_policies: bool = Field(
        alias="apply-scv-on-simplified-mode-fw-policies",
        description="""Determine whether the gateway verifies that remote access clients are securely configured. This is set here only if the security policy is defined in the Simplified Mode. If the security policy is defined in the Traditional Mode, verification takes place per rule.""",
    )
    exceptions: Add | Remove | ScvExceptionsRequest | list[dict] = Field(
        alias="exceptions",
        description="""Specify the hosts that can be accessed using the selected services even if the client is not verified.<br>Available only if apply-scv-on-simplified-mode-fw-policies is true.""",
    )
    no_scv_for_unsupported_cp_clients: bool = Field(
        alias="no-scv-for-unsupported-cp-clients",
        description="""Do not apply Secure Configuration Verification for connections from Check Point VPN clients that don't support it, such as SSL Network Extender, GO, Capsule VPN / Connect, Endpoint Connects lower than R75, or L2TP clients.<br>Available only if apply-scv-on-simplified-mode-fw-policies is true.""",
    )
    upon_verification_accept_and_log_client_connection: bool = Field(
        alias="upon-verification-accept-and-log-client-connection",
        description="""If the gateway verifies the client's configuration, decide how the gateway should handle connections with clients that fail the Security Configuration Verification. It is possible to either drop the connection or Accept the connection and log it.""",
    )
    only_tcp_ip_protocols_are_used: bool = Field(
        alias="only-tcp-ip-protocols-are-used",
        description="""Most SCV checks are configured via the SCV policy. Specify whether to verify that  only TCP/IP protocols are used.""",
    )
    policy_installed_on_all_interfaces: bool = Field(
        alias="policy-installed-on-all-interfaces",
        description="""Most SCV checks are configured via the SCV policy. Specify whether to verify that  the Desktop Security Policy is installed on all the interfaces of the client.""",
    )
    generate_log: bool = Field(
        alias="generate-log",
        description="""If the client identifies that the secure configuration has been violated, select whether a log is generated by the remote access client and sent to the Security Management server.""",
    )
    notify_user: bool = Field(
        alias="notify-user",
        description="""If the client identifies that the secure configuration has been violated, select whether to user should be notified.""",
    )
