[project]
name = "async_checkpoint-sdk"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.14.3",
    "orjson>=3.11.9",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
    #"docstring-generator>=2.1.0",
    "ruff>=0.16.1",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13"]
build-backend = "uv_build"

[tool.ruff]
line-length = 100
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 80

[checkpoint.config]
server = ""
port = 80
password = ""
username = ""
api-key = ""
